# Generated by Django 2.2.6 on 2019-10-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0006_auto_20191017_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='categories',
            field=models.ManyToManyField(blank=True, to='donation.Category'),
        ),
    ]
